/** Local, compressed issuer artwork. Provenance: public/company-logos/manifest.json. */
const companyLogos = [
  [
    "xstocks",
    "AAPLx",
    "AAPL",
    "aapl.webp",
    "XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp",
  ],
  [
    "xstocks",
    "ABBVx",
    "ABBV",
    "abbv.webp",
    "XswbinNKyPmzTa5CskMbCPvMW6G5CMnZXZEeQSSQoie",
  ],
  [
    "xstocks",
    "AMDx",
    "AMD",
    "amd.webp",
    "XsXcJ6GZ9kVnjqGsjBnktRcuwMBmvKWh8S93RefZ1rF",
  ],
  [
    "xstocks",
    "AMZNx",
    "AMZN",
    "amzn.webp",
    "Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg",
  ],
  [
    "xstocks",
    "ASMLx",
    "ASML",
    "asml.webp",
    "XshuHQ6o6SVpUNawvnnTMxsZ4tacZsNgVCLorv7TkFq",
  ],
  [
    "xstocks",
    "AVGOx",
    "AVGO",
    "avgo.webp",
    "XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo",
  ],
  [
    "xstocks",
    "CATx",
    "CAT",
    "cat.webp",
    "XsRvd1meWQ9kW1SrZPa1jokQqmBoPWWjd6wGTgdp5E6",
  ],
  [
    "xstocks",
    "COPx",
    "COP",
    "cop.webp",
    "Xs58CxmUcgT17reeVV64se747XuRfjsJQnpb8DX9TDq",
  ],
  [
    "xstocks",
    "CRMx",
    "CRM",
    "crm.webp",
    "XsczbcQ3zfcgAEt9qHQES8pxKAVG5rujPSHQEXi4kaN",
  ],
  [
    "xstocks",
    "CVXx",
    "CVX",
    "cvx.webp",
    "XsNNMt7WTNA2sV3jrb1NNfNgapxRF5i4i6GcnTRRHts",
  ],
  [
    "xstocks",
    "DEx",
    "DE",
    "de.webp",
    "Xsh3Lt6pLpH65udstiFuZThJ6gyQTL6ryVXtNwEy5zd",
  ],
  [
    "xstocks",
    "GEx",
    "GE",
    "ge.webp",
    "XsfsBjSZoXXKJsxoSt8TyLYsjhBAKFaDPZTCQbFRirP",
  ],
  [
    "xstocks",
    "GLDx",
    "GLD",
    "gld.webp",
    "Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re",
  ],
  [
    "xstocks",
    "GOOGLx",
    "GOOGL",
    "googl.webp",
    "XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN",
  ],
  [
    "xstocks",
    "GSx",
    "GS",
    "gs.webp",
    "XsgaUyp4jd1fNBCxgtTKkW64xnnhQcvgaxzsbAq5ZD1",
  ],
  [
    "xstocks",
    "HONx",
    "HON",
    "hon.webp",
    "XsRbLZthfABAPAfumWNEJhPyiKDW6TvDVeAeW7oKqA2",
  ],
  [
    "xstocks",
    "JNJx",
    "JNJ",
    "jnj.webp",
    "XsGVi5eo1Dh2zUpic4qACcjuWGjNv8GCt3dm5XcX6Dn",
  ],
  [
    "xstocks",
    "JPMx",
    "JPM",
    "jpm.webp",
    "XsMAqkcKsUewDrzVkait4e5u4y8REgtyS7jWgCpLV2C",
  ],
  [
    "xstocks",
    "KOx",
    "KO",
    "ko.webp",
    "XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ",
  ],
  [
    "xstocks",
    "LLYx",
    "LLY",
    "lly.webp",
    "Xsnuv4omNoHozR6EEW5mXkw8Nrny5rB3jVfLqi6gKMH",
  ],
  [
    "xstocks",
    "LMTx",
    "LMT",
    "lmt.webp",
    "XssULacY8D3z3a8HoQuLid8wdJHcZLGpSST9MkNFzox",
  ],
  [
    "xstocks",
    "MAx",
    "MA",
    "ma.webp",
    "XsApJFV9MAktqnAc6jqzsHVujxkGm9xcSUffaBoYLKC",
  ],
  [
    "xstocks",
    "MCDx",
    "MCD",
    "mcd.webp",
    "XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2",
  ],
  [
    "xstocks",
    "METAx",
    "META",
    "meta.webp",
    "Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu",
  ],
  [
    "xstocks",
    "MRKx",
    "MRK",
    "mrk.webp",
    "XsnQnU7AdbRZYe2akqqpibDdXjkieGFfSkbkjX1Sd1X",
  ],
  [
    "xstocks",
    "MSFTx",
    "MSFT",
    "msft.webp",
    "XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX",
  ],
  [
    "xstocks",
    "NOCx",
    "NOC",
    "noc.webp",
    "Xs1eyZcwrzzYW3hDjfpm7PiJrC9RyFszsHpqfTeUTCE",
  ],
  [
    "xstocks",
    "NOWx",
    "NOW",
    "now.webp",
    "XsBnEFd2EtpwBRNVfN8qLZcVUnuqXRaGCSEEFChLfxL",
  ],
  [
    "xstocks",
    "NVDAx",
    "NVDA",
    "nvda.webp",
    "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh",
  ],
  [
    "xstocks",
    "ORCLx",
    "ORCL",
    "orcl.webp",
    "XsjFwUPiLofddX5cWFHW35GCbXcSu1BCUGfxoQAQjeL",
  ],
  [
    "xstocks",
    "PLTRx",
    "PLTR",
    "pltr.webp",
    "XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4",
  ],
  [
    "prestocks",
    "ANDURIL",
    "ANDURIL",
    "pre-anduril.webp",
    "PresTj4Yc2bAR197Er7wz4UUKSfqt6FryBEdAriBoQB",
  ],
  [
    "prestocks",
    "ANTHROPIC",
    "ANTHROPIC",
    "pre-anthropic.webp",
    "Pren1FvFX6J3E4kXhJuCiAD5aDmGEb7qJRncwA8Lkhw",
  ],
  [
    "prestocks",
    "FIGUREAI",
    "FIGUREAI",
    "pre-figureai.webp",
    "PreZad18qfPtbxNpMtMuAuX2zVpvkEU8DnJx56faCWd",
  ],
  [
    "prestocks",
    "KALSHI",
    "KALSHI",
    "pre-kalshi.webp",
    "PreLWGkkeqG1s4HEfFZSy9moCrJ7btsHuUtfcCeoRua",
  ],
  [
    "prestocks",
    "NEURALINK",
    "NEURALINK",
    "pre-neuralink.webp",
    "PrekqLJvJ3qVdXmBGDiexvwUTF4rLFDa6HWS4HJbw9S",
  ],
  [
    "prestocks",
    "OPENAI",
    "OPENAI",
    "pre-openai.webp",
    "PreweJYECqtQwBtpxHL171nL2K6umo692gTm7Q3rpgF",
  ],
  [
    "prestocks",
    "POLYMARKET",
    "POLYMARKET",
    "pre-polymarket.webp",
    "Pre8AREmFPtoJFT8mQSXQLh56cwJmM7CFDRuoGBZiUP",
  ],
  [
    "prestocks",
    "SPACEX",
    "SPACEX",
    "pre-spacex.webp",
    "PreANxuXjsy2pvisWWMNB6YaJNzr7681wJJr2rHsfTh",
  ],
  [
    "prestocks",
    "XAI",
    "XAI",
    "pre-xai.webp",
    "PreC1KtJ1sBPPqaeeqL6Qb15GTLCYVvyYEwxhdfTwfx",
  ],
  [
    "xstocks",
    "QQQx",
    "QQQ",
    "qqq.webp",
    "Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ",
  ],
  [
    "xstocks",
    "RTXx",
    "RTX",
    "rtx.webp",
    "XsN53tgjZA4QU8iuedPNHxxCbDqKcJqbrT1f8jBXzdC",
  ],
  [
    "xstocks",
    "SBUXx",
    "SBUX",
    "sbux.webp",
    "Xs9gd8SGbYQn9kkUYQayn46BdqQbvvUshEF6ZpRAzM7",
  ],
  [
    "xstocks",
    "SPYx",
    "SPY",
    "spy.webp",
    "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W",
  ],
  [
    "xstocks",
    "TSLAx",
    "TSLA",
    "tsla.webp",
    "XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB",
  ],
  [
    "xstocks",
    "TSMx",
    "TSM",
    "tsm.webp",
    "XsafvsGtzFqqHgTnA3aPC83EAMkacU5mcGtcSayhpVV",
  ],
  [
    "xstocks",
    "UNHx",
    "UNH",
    "unh.webp",
    "XszvaiXGPwvk2nwb3o9C1CX4K6zH8sez11E6uyup6fe",
  ],
  [
    "xstocks",
    "Vx",
    "V",
    "v.webp",
    "XsqgsbXwWogGJsNcVZ3TyVouy2MbTkfCFhCGGGcQZ2p",
  ],
  [
    "xstocks",
    "XOMx",
    "XOM",
    "xom.webp",
    "XsaHND8sHyfMfsWPj6kSdd5VwvCayZvjYgKmmcNL5qh",
  ],
] as const;

const byMint = new Map<string, string>();
const byIssuerSymbol = new Map<string, string>();
for (const [issuer, symbol, underlyingSymbol, file, mint] of companyLogos) {
  const path = `/company-logos/${file}`;
  byMint.set(mint, path);
  byIssuerSymbol.set(`${issuer}:${symbol.toUpperCase()}`, path);
  byIssuerSymbol.set(`${issuer}:${underlyingSymbol.toUpperCase()}`, path);
}

/** Mint identity takes precedence so unrelated tokens cannot borrow company branding. */
export function getCompanyLogo(asset: {
  symbol: string;
  mint?: string;
  issuer?: string;
  underlyingSymbol?: string;
}): string | null {
  if (asset.mint) return byMint.get(asset.mint) ?? null;
  if (!asset.issuer) return null;
  return (
    byIssuerSymbol.get(
      `${asset.issuer}:${(asset.underlyingSymbol || asset.symbol).toUpperCase()}`,
    ) ?? null
  );
}
