[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
kite_vault = "WUrZqhZgSHZ8R8F6zV4CD3LQUXUWffpkZQf6zBCCmEa"

[programs.devnet]
kite_vault = "WUrZqhZgSHZ8R8F6zV4CD3LQUXUWffpkZQf6zBCCmEa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/utkarsh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
