[toolchain]
solana_version = "4.0.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
kite_guard = "8Fm9HENPAFnyo6L8cHJFx62HHsZ6ez6CPUDuzgKAzrjs"

[programs.localnet]
kite_guard = "8Fm9HENPAFnyo6L8cHJFx62HHsZ6ez6CPUDuzgKAzrjs"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm test"

[hooks]
